exports[`Single Select : CSS : classes : generates selector string : span.nav2 1`] = "span.nav2";
exports[`Single Select : CSS : classes : generates selector string : span.nav1.active 1`] = "span.nav1.active";
exports[`Single Select : CSS : classes : generates selector string : span.hidden 1`] = "span.hidden";
exports[`Single Select : CSS : id : generates selector string : span#first 1`] = "span#first";
exports[`Single Select : CSS : id : generates selector string : span#second 1`] = "span#second";
exports[`Single Select : CSS : href : generates selector string : a[href="/main"] 1`] = "a[href=\"\\/main\"]";
exports[`Single Select : CSS : href : generates selector string : a[href="/home"] 1`] = "a[href=\"\\/home\"]";
exports[`Single Select : CSS : href : generates selector string : body > a:nth-child(3) 1`] = "body a:nth-of-type(3)";
exports[`Single Select : CSS : attributes : generates selector string : body > span:nth-child(1) 1`] = "body span:nth-of-type(1)";
exports[`Single Select : CSS : attributes : generates selector string : span[title="two"] 1`] = "span[title=\"two\"]";
exports[`Single Select : CSS : attributes : generates selector string : span.nav2 1`] = "span.nav2";
exports[`Single Select : CSS : contains : generates selector string : body > div:nth-child(1) 1`] = "body > div:nth-of-type(1)";
exports[`Single Select : CSS : contains : generates selector string : body > div:nth-child(2) 1`] = "body div:nth-of-type(2)";
exports[`Single Select : CSS : contains : generates selector string : body > div:nth-child(3) 1`] = "body div:nth-of-type(3)";
exports[`Single Select : CSS : contains : generates selector string : body > div:nth-child(4) 1`] = "body div:nth-of-type(4)";
exports[`Single Select : CSS : contains : generates selector string : body > div:nth-child(4) div 1`] = "body div:nth-of-type(4) div";
exports[`Single Select : XPath : classes : generates selector string : span.nav2 1`] = ".//span[contains(concat(\" \",normalize-space(@class),\" \"),\" nav2 \")]";
exports[`Single Select : XPath : classes : generates selector string : span.nav1.active 1`] = ".//span[contains(concat(\" \",normalize-space(@class),\" \"),\" nav1 \")][contains(concat(\" \",normalize-space(@class),\" \"),\" active \")]";
exports[`Single Select : XPath : classes : generates selector string : span.hidden 1`] = ".//span[contains(concat(\" \",normalize-space(@class),\" \"),\" hidden \")]";
exports[`Single Select : XPath : id : generates selector string : span#first 1`] = ".//span[@id=\"first\"]";
exports[`Single Select : XPath : id : generates selector string : span#second 1`] = ".//span[@id=\"second\"]";
exports[`Single Select : XPath : href : generates selector string : a[href="/main"] 1`] = ".//a[@href=\"/main\"]";
exports[`Single Select : XPath : href : generates selector string : a[href="/home"] 1`] = ".//a[@href=\"/home\"]";
exports[`Single Select : XPath : href : generates selector string : body > a:nth-child(3) 1`] = ".//body//a[3]";
exports[`Single Select : XPath : attributes : generates selector string : body > span:nth-child(1) 1`] = ".//body//span[1]";
exports[`Single Select : XPath : attributes : generates selector string : span[title="two"] 1`] = ".//span[@title=\"two\"]";
exports[`Single Select : XPath : attributes : generates selector string : span.nav2 1`] = ".//span[contains(concat(\" \",normalize-space(@class),\" \"),\" nav2 \")]";
exports[`Single Select : XPath : contains : generates selector string : body > div:nth-child(1) 1`] = ".//body//div[contains(text(),\"first\")]";
exports[`Single Select : XPath : contains : generates selector string : body > div:nth-child(2) 1`] = ".//body//div[contains(text(),\"second\")]";
exports[`Single Select : XPath : contains : generates selector string : body > div:nth-child(3) 1`] = ".//body//div[contains(text(),\"third\")]";
exports[`Single Select : XPath : contains : generates selector string : body > div:nth-child(4) 1`] = ".//body//div[.//div]";
exports[`Single Select : XPath : contains : generates selector string : body > div:nth-child(4) div 1`] = ".//body//div//div";
exports[`Single Select : jQuery : classes : generates selector string : span.nav2 1`] = "span.nav2";
exports[`Single Select : jQuery : classes : generates selector string : span.nav1.active 1`] = "span.nav1.active";
exports[`Single Select : jQuery : classes : generates selector string : span.hidden 1`] = "span.hidden";
exports[`Single Select : jQuery : id : generates selector string : span#first 1`] = "span#first";
exports[`Single Select : jQuery : id : generates selector string : span#second 1`] = "span#second";
exports[`Single Select : jQuery : href : generates selector string : a[href="/main"] 1`] = "a[href=\"\\/main\"]";
exports[`Single Select : jQuery : href : generates selector string : a[href="/home"] 1`] = "a[href=\"\\/home\"]";
exports[`Single Select : jQuery : href : generates selector string : body > a:nth-child(3) 1`] = "body a:nth-of-type(3)";
exports[`Single Select : jQuery : attributes : generates selector string : body > span:nth-child(1) 1`] = "body span:nth-of-type(1)";
exports[`Single Select : jQuery : attributes : generates selector string : span[title="two"] 1`] = "span[title=\"two\"]";
exports[`Single Select : jQuery : attributes : generates selector string : span.nav2 1`] = "span.nav2";
exports[`Single Select : jQuery : contains : generates selector string : body > div:nth-child(1) 1`] = "body div:contains(\"first\")";
exports[`Single Select : jQuery : contains : generates selector string : body > div:nth-child(2) 1`] = "body div:contains(\"second\")";
exports[`Single Select : jQuery : contains : generates selector string : body > div:nth-child(3) 1`] = "body div:contains(\"third\")";
exports[`Single Select : jQuery : contains : generates selector string : body > div:nth-child(4) 1`] = "body div:contains(\"forth one\")";
exports[`Single Select : jQuery : contains : generates selector string : body > div:nth-child(4) div 1`] = "body div div";
